<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxisTune.Core\AxisTune.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ppy.SDL3-CS" Version="2026.623.0" />
  </ItemGroup>

</Project>
